# Generated by Django 4.2.13 on 2024-06-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minder', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_movies',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_movies',
            field=models.ManyToManyField(to='minder.movie'),
        ),
    ]
